import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        MergeSort mergeSort=new MergeSort();

        int [] arr = {8, 4, 23, 42, 16, 15};
        mergeSort.sort(arr);

        int[] test= new  int [arr.length];
        for (int i=0; i<arr.length ;i++){
            System.out.println(arr[i]);
         test[i]=arr[i];
        }
        System.out.println(Arrays.toString(test));
        int[] arr1={20,18,12,8,5,-2};
        int[] arr2={5,12,7,5,5,7};
        int[] arr3={2,3,5,7,13,11};
        mergeSort.sort(arr1);
        mergeSort.sort(arr2);
        mergeSort.sort(arr3);
        System.out.println(Arrays.toString(arr1));
        System.out.println(Arrays.toString(arr2));
        System.out.println(Arrays.toString(arr3));
    }
}
