/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//
        Graph <Integer> graph=new Graph <Integer>();
graph.addNewEdge(0, 1);
graph.addNewEdge(0, 4);
graph.addNewEdge(1, 2);
graph.addNewEdge(1, 3);
graph.addNewEdge(1, 4);
graph.addNewEdge(2, 3);
graph.addNewEdge(2, 4);
graph.addNewEdge(3, 0);
graph.addNewEdge(2, 0);
graph.addNewNode(5);
        System.out.println(graph.getNodes());

System.out.println("Adjacency List for the graph:\n"+ graph.toString());
        System.out.println(graph.getNeighbors(1));
        System.out.println("number of nodes "+graph.size());
    }
}