/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test void pushStackTest() {
        Stack<Integer> sl = new Stack<>();
        sl.push(1);
        sl.push(2);
        assertEquals( "Top -->  { 1 } -->   { 2 } -->  Null" , sl.toString());
    }
}
