/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashTable<String>ht=new HashTable<>(1024);
        ht.add(11,"amman");
//        System.out.println(ht.get(11));
        ht.add(51,"zarqa");
        ht.add(1,"irbid");
        ht.add(11,"aqaba");
//        System.out.println(ht.get(51));
        System.out.println(ht.get(11));
        System.out.println(ht.toString());
//        System.out.println(ht.contains(1));
//        System.out.println(ht.contains(51));
//        System.out.println(ht.contains(114));
//        System.out.println(ht.contains(12));

    }
}
