import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        InsertionSort insertionSort=new InsertionSort();

        int [] arr = {8,4,23,42,16,15};
        int [] arr1 = {20,18,12,8,5,-2};
        int [] arr2 = {5,12,7,5,5,7};
        int [] arr3 = {2,3,5,7,13,11};

        System.out.println(Arrays.toString(insertionSort.insertionSort(arr)));
        System.out.println(Arrays.toString(insertionSort.insertionSort(arr1)));
        System.out.println(Arrays.toString(insertionSort.insertionSort(arr2)));
        System.out.println(Arrays.toString(insertionSort.insertionSort(arr3)));
    }
}
