/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void test(){
        MergeSort mergeSort=new MergeSort();
        int [] arr = {8, 4, 23, 42, 16, 15};
        mergeSort.sort(arr);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(arr));
    }
    @Test public void reverseSorted(){
        MergeSort mergeSort=new MergeSort();
        int[] arr1={20,18,12,8,5,-2};
        mergeSort.sort(arr1);
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(arr1));
    }
    @Test public void fewUniques(){
        MergeSort mergeSort=new MergeSort();
        int[] arr2={5,12,7,5,5,7};
        mergeSort.sort(arr2);
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(arr2));
    }
    @Test public void testNearlySorted(){
        MergeSort mergeSort=new MergeSort();
        int[] arr3={2,3,5,7,13,11};
        mergeSort.sort(arr3);
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(arr3));
    }
}
