/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println("------------------Stack------------------");
        Stack<Integer> sl = new Stack<>();
        sl.push(1);
        sl.push(2);
        sl.push(3);
        sl.push(4);
        System.out.println("------------------push Stack------------------");
        System.out.println(sl );
        System.out.println("------------------pop Stack------------------");
        sl.pop();
        System.out.println(sl);
        System.out.println("------------------peek Stack------------------");
        System.out.println(sl.peek());
        System.out.println("------------------isempty Stack------------------");
        System.out.println(sl.isEmpty());
        System.out.println("-------------------------------------------");
        System.out.println("------------------Queue-----------------");
        System.out.println("-------------------------------------------");
        Queue<Integer> ql = new Queue<>();
        ql.enqueue(1);
        ql.enqueue(2);
        ql.enqueue(3);
        ql.enqueue(4);
        System.out.println("------------------enqueue-----------------");
        System.out.println(ql);
        System.out.println("-------------------dequeue------------------");
        ql.dequeue();
        System.out.println(ql);
        System.out.println("------------------peek------------------");
        System.out.println(ql.peek());
        System.out.println("------------------isempty--------------------");
        System.out.println(ql.isEmpty());
        System.out.println("-------------------------------------------");
        System.out.println("------------------Pseudo--------------------");
        System.out.println("-------------------------------------------");

        Pseudo pseudo = new Pseudo();
        pseudo.enqueue(1);
        pseudo.enqueue(2);
        pseudo.enqueue(3);
        pseudo.enqueue(4);
        System.out.println("------------------enqueue--------------------");
        System.out.println(pseudo.stack1.toString());
        pseudo.dequeue();
        System.out.println("------------------dequeue--------------------");
        System.out.println(pseudo.stack1.toString());
    }
}
