/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void addTest(){
        HashTable<String>ht=new HashTable<>(1024);
        ht.add(11,"amman");
        ht.add(51,"zarqa");
        ht.add(1,"irbid");
        assertEquals("zarqa",(ht.get(51)));
        assertEquals("irbid",(ht.get(1)));
    }
    @Test public void  keyThatDoesNotExist(){
        HashTable<String>ht=new HashTable<>(1024);
        ht.add(17,"amman");

        assertEquals(null,(ht.get(19)));
    }

@Test public void collision(){
    HashTable<String>ht=new HashTable<>(1024);
    ht.add(17,"amman");
    assertEquals("amman",(ht.get(17)));
    ht.add(17,"zarqa");
    assertEquals("zarqa",(ht.get(17)));

}
@Test public void hashTest(){
    HashTable<String>ht=new HashTable<>(1024);
    ht.hash(1000);
    assertEquals(984,ht.hash(1000));
}
}
